FROM python:3.8-slim

#RUN mkdir -p api/ 
#WORKDIR /api/
#RUN printf "HOST=\nPORT=" >.env
RUN mkdir -p /trips-api 
COPY . /trips-api/
WORKDIR /trips-api


ENV PYTHONPATH=${PYTHONPATH}:${PWD} 

RUN pip3 install poetry
RUN poetry config virtualenvs.create false
RUN poetry install --no-interaction --no-ansi
CMD python3 -m pytest ./test