version: 1

formatters:
    standard:
        format: '%(asctime)s %(levelname)-8s %(name)-15s %(message)s'
        datefmt: '%Y-%m-%d %H:%M:%S'

    brief:
        format: '%(message)s'

handlers:
    console:
        class: logging.StreamHandler
        formatter: standard
        level: WARNING
        stream: ext://sys.stdout
    file:
        class : logging.handlers.RotatingFileHandler
        formatter: standard
        filename: logs/logconfig.log
        maxBytes: 1024
        backupCount: 3

loggers:
    root:
        handlers: [console]
        level: WARNING
